### ISSUE TITLE
Ray calculations at planar refraction interface seem to be off

### ISSUE THREAD

**Issue by joekkrause** [StellarSoftwareBerkeley/BeamFour#2]
![2d_plot_of_final_rays](https://user-images.githubusercontent.com/44128128/46912021-6f2b6300-cf39-11e8-9805-456f24b144c5.png)
![layout_ray_refracting_example](https://user-images.githubusercontent.com/44128128/46912022-6f2b6300-cf39-11e8-944b-4da7ef66391f.png)

[example_ray_refraction_issue.zip](https://github.com/StellarSoftwareBerkeley/BeamFour/files/2476049/example_ray_refraction_issue.zip)

Please find the attached files with a working example of the issue.  It appears that somehow that rays that have an angle in the direction of the y axis, but not in the x axis acquire a nonlinear angle after going from a higher to a lower index of refraction material that has a pitch.  The two dimensional plot seems to indicate that the nonlinear angle is in the shape of a cosine or parabolic type curve as plotted against the deviation angle on the y-axis.  I am assuming this is not correct operation since the angle perpendicular to the plane of incidence should not affect the refracted angle in the plane of incidence...  Of course I could be wrong and would be happy to see a reference showing me why this should be expected.
Thank you for your help, the software is helpful in modeling optical setups.

Joe

**Comment by MikeLampton** [comment]
Hi Joe,

Your optics file looks like this..





What is says is, rays approaching your first surface are initially travelling through sapphire.

Yes?

Then, you  approach your second surface in an index = 1 = air.

Yes?

Then, your rays approach your third surface, also in air (index = blank = default 1.0).

Yes?

So you have a peculiar lens, made of air, illuminating your Z=25mm final surface,
also through air?

Seems odd to me.

See examples 9.1 and 9.7 in the B4Guide, see if they help.

Cheers
Mike Lampton



Michael Lampton
info@stellarsoftware.com
AST:7731^29u18e3

**Comment by MikeLampton** [comment]
The introductory part of Chapter 9 looks like this...





Could be helpful,
Mike

Michael Lampton
info@stellarsoftware.com
AST:7731^29u18e3

**Comment by joekkrause** [comment]
The interesting thing is that the rays start in the sapphire, then diverge
from a point in the same plane (x = 0) with different angles in the y axis
direction and travel to the flat surface.  I was expecting to see all of
the rays bent in the x direction the same amount since I thought the
deviation in the x axis direction only depended on the ray angle normal to
the surface in the x axis direction.  I also simulated the critical angle.
For the pitch of the surface of the sapphire = 0 degrees, the critical
angle matches theory.  However once I put a couple degree pitch on the exit
surface of the sapphire the critical angle gets smaller.  I don't
understand how the pitch of the surface effects the critical angle in the y
direction perpendicular to the surface pitch...  I reduced the example to
remove a few more items.  I looked at the chapter 9.1 example, and it is
similar to what I'm trying to accomplish, but I only have a flat
surface...  I was not expecting a lens type pattern from a flat plane of
rays hitting a flat sapphire to air interface...  I suspect there may be
something wrong with the ray tracing algorithm in this situation.

**Comment by MikeLampton** [comment]
Thank you Joe Krause,
But what is that second surface doing?
It seems to be a flat lens surface with air on both sides?
-Mike


Michael Lampton
info@stellarsoftware.com
AST:7731^29u18e3

**Comment by joekkrause** [comment]
Hello,
      Thank you for you patience.  I think I figured out what is going on.  I was confusing the plane of incidence with the plane of rays that I created.  The rays diverge similar to a lens since the plane of incidence is the individual ray and the normal to the surface.  So, the point source I created in the middle of some Sapphire can only exit a circular window of angles.  Apparently this effect is called Snell's window.  So, I think this issue is closed, and I definitely learned something new...

**Comment by MikeLampton** [comment]
17 October 

Hi Joe,

Hecht & Zajac's book "Optics" has a nice description about
total internal reflection, which keeps rays from refracting out of
an optically denser medium if they arrive at the surface with
more than the critical angle off the surface normal. In two
dimensions Snell's law tells us that 

sin(Aout) = N * sin(Ain)

The left hand side cannot exceed 1, but the right hand side can.
So AinCritical = arcsin(1/N).  I attach one page of Hecht & Zajac.

In BEAM FOUR, I set up your situation in SNELL.OPT and SNELL.RAY
that demonstrate this refraction for your case of a pitched flat exit
surface.  I chose pitch 30 degrees.  You can explore various other
situations in BEAM FOUR (fully 3D, not just Snell's 2D formula)
and in EXCEL, worksheet attached (Snell's 2D only).

Hope this helps,

Mike







Michael Lampton
info@stellarsoftware.com
AST:7731^29u18e3

**Comment by joekkrause** [comment]
Hi Mike,
     Thank you for your insight.  It seems that your attachments are
missing from your last response.  Would you mind sending them to me again?
I have the Hecht book versions 2 and 4, so you can just let me know what
page the example is on.  I would be interested in seeing the snell.opt and
snell.ray and spreadsheet files you had mentioned.

Thank you again for your help,
Joe

**Comment by MikeLampton** [comment]
Sure.
Don't know how those attachments fell off.
Page 82 of Hecht and Zajac.




Michael Lampton
info@stellarsoftware.com
AST:7731^29u18e3
