### ISSUE TITLE
Update this organization name

### ISSUE THREAD

**Issue by Neustradamus** [StellarSoftwareBerkeley/BeamFour#5]
Can you change the StellarSoftwareBerkeley organization name?

Currently, it is noted "Mike Lampton" instead of "Stellar Software".

Thanks in advance.

PS : A personal account can be for Mike Lampton.

**Comment by jenlampton** [comment]
done.

**Comment by Neustradamus** [comment]
@jenlampton: Thanks a lot!
Never too late :)
